-- PROTHEUS1233_HML.dbo.SG1010 definition

-- Drop table

-- DROP TABLE PROTHEUS1233_HML.dbo.SG1010;

CREATE TABLE master.dbo.SG1010 (
	G1_FILIAL varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	G1_COD varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	G1_COMP varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	G1_TRT varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	G1_XUM varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	G1_QUANT float DEFAULT 0 NOT NULL,
	G1_PERDA float DEFAULT 0 NOT NULL,
	G1_INI varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	G1_FIM varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	G1_OBSERV varchar(45) COLLATE Latin1_General_100_BIN DEFAULT '                                             ' NOT NULL,
	G1_FIXVAR varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	G1_GROPC varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	G1_OPC varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	G1_REVINI varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	G1_NIV varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	G1_NIVINV varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	G1_REVFIM varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	G1_OK varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	G1_POTENCI float DEFAULT 0 NOT NULL,
	G1_TIPVEC varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	G1_VECTOR varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	G1_VLCOMPE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	G1_LOCCONS varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	G1_USAALT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	G1_FANTASM varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	G1_LISTA varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	D_E_L_E_T_ varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	R_E_C_N_O_ bigint DEFAULT 0 NOT NULL,
	R_E_C_D_E_L_ bigint DEFAULT 0 NOT NULL,
	CONSTRAINT SG1010_PK PRIMARY KEY (R_E_C_N_O_)
);
 CREATE NONCLUSTERED INDEX SG10101 ON dbo.SG1010 (  G1_FILIAL ASC  , G1_COD ASC  , G1_COMP ASC  , G1_TRT ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SG10102 ON dbo.SG1010 (  G1_FILIAL ASC  , G1_COMP ASC  , G1_COD ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SG10103 ON dbo.SG1010 (  G1_FILIAL ASC  , G1_COD ASC  , G1_GROPC ASC  , G1_OPC ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SG10104 ON dbo.SG1010 (  G1_FILIAL ASC  , G1_TIPVEC ASC  , G1_VECTOR ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SG10105 ON dbo.SG1010 (  G1_FILIAL ASC  , G1_COD ASC  , G1_FIM ASC  , G1_TRT ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE  UNIQUE NONCLUSTERED INDEX SG1010_UNQ ON dbo.SG1010 (  G1_FILIAL ASC  , G1_COD ASC  , G1_COMP ASC  , G1_TRT ASC  , G1_INI ASC  , G1_FIM ASC  , G1_REVINI ASC  , G1_REVFIM ASC  , R_E_C_D_E_L_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
	 
	
	
	
	
	
-- PROTHEUS1233_HML.dbo.SB1010 definition

-- Drop table

-- DROP TABLE PROTHEUS1233_HML.dbo.SB1010;

CREATE TABLE master.dbo.SB1010 (
	B1_AFAMAD float DEFAULT 0 NOT NULL,
	B1_FILIAL varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	B1_COD varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_DESC varchar(100) COLLATE Latin1_General_100_BIN DEFAULT '                                                                                                    ' NOT NULL,
	B1_XDESC2 varchar(60) COLLATE Latin1_General_100_BIN DEFAULT '                                                            ' NOT NULL,
	B1_CODITE varchar(27) COLLATE Latin1_General_100_BIN DEFAULT '                           ' NOT NULL,
	B1_TIPO varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_UM varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_LOCPAD varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_GRUPO varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	B1_ZZLOCAL varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_POSIPI varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_ESPECIE varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_EX_NCM varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_EX_NBM varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_PICM float DEFAULT 0 NOT NULL,
	B1_IPI float DEFAULT 0 NOT NULL,
	B1_ALIQISS float DEFAULT 0 NOT NULL,
	B1_CODISS varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_TE varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_TS varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_PICMRET float DEFAULT 0 NOT NULL,
	B1_BITMAP varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_SEGUM varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_PICMENT float DEFAULT 0 NOT NULL,
	B1_IMPZFRC varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CONV float DEFAULT 0 NOT NULL,
	B1_TIPCONV varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ALTER varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_QE float DEFAULT 0 NOT NULL,
	B1_PRV1 float DEFAULT 0 NOT NULL,
	B1_EMIN float DEFAULT 0 NOT NULL,
	B1_CUSTD float DEFAULT 0 NOT NULL,
	B1_UCALSTD varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_UCOM varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_UPRC float DEFAULT 0 NOT NULL,
	B1_MCUSTD varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ESTFOR varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_PESO float DEFAULT 0 NOT NULL,
	B1_ESTSEG float DEFAULT 0 NOT NULL,
	B1_FORPRZ varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_PE float DEFAULT 0 NOT NULL,
	B1_TIPE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_LE float DEFAULT 0 NOT NULL,
	B1_LM float DEFAULT 0 NOT NULL,
	B1_CONTA varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_TOLER float DEFAULT 0 NOT NULL,
	B1_CC varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_ITEMCC varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_PROC varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_LOJPROC varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_FAMILIA varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_QB float DEFAULT 0 NOT NULL,
	B1_APROPRI varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_TIPODEC varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ORIGEM varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CLASFIS varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_UREV varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_DATREF varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_FANTASM varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_RASTRO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_FORAEST varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_COMIS float DEFAULT 0 NOT NULL,
	B1_DTREFP1 varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_MONO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PERINV float DEFAULT 0 NOT NULL,
	B1_GRTRIB varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_MRP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_NOTAMIN float DEFAULT 0 NOT NULL,
	B1_CONINI varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_CONTSOC varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PRVALID float DEFAULT 0 NOT NULL,
	B1_CODBAR varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_GRADE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_NUMCOP float DEFAULT 0 NOT NULL,
	B1_FORMLOT varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_IRRF varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_FPCOD varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_CODGTIN varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_DESC_P varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_CONTRAT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_DESC_GI varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_DESC_I varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_LOCALIZ varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_OPERPAD varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_ANUENTE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_OPC varchar(80) COLLATE Latin1_General_100_BIN DEFAULT '                                                                                ' NOT NULL,
	B1_CODOBS varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_VLREFUS float DEFAULT 0 NOT NULL,
	B1_IMPORT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_FABRIC varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_SITPROD varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_MODELO varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_SETOR varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_PRODPAI varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_BALANCA varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_TECLA varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_DESPIMP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_TIPOCQ varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_SOLICIT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_GRUPCOM varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_QUADPRO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_BASE3 varchar(14) COLLATE Latin1_General_100_BIN DEFAULT '              ' NOT NULL,
	B1_DESBSE3 varchar(60) COLLATE Latin1_General_100_BIN DEFAULT '                                                            ' NOT NULL,
	B1_AGREGCU varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_NUMCQPR float DEFAULT 0 NOT NULL,
	B1_CONTCQP float DEFAULT 0 NOT NULL,
	B1_REVATU varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_CODEMB varchar(30) COLLATE Latin1_General_100_BIN DEFAULT '                              ' NOT NULL,
	B1_INSS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ESPECIF varchar(80) COLLATE Latin1_General_100_BIN DEFAULT '                                                                                ' NOT NULL,
	B1_NALNCCA varchar(7) COLLATE Latin1_General_100_BIN DEFAULT '       ' NOT NULL,
	B1_MAT_PRI varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_NALSH varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_REDINSS float DEFAULT 0 NOT NULL,
	B1_REDIRRF float DEFAULT 0 NOT NULL,
	B1_ALADI varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_TAB_IPI varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_GRUDES varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_DATASUB varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_REDPIS float DEFAULT 0 NOT NULL,
	B1_REDCOF float DEFAULT 0 NOT NULL,
	B1_PCSLL float DEFAULT 0 NOT NULL,
	B1_PCOFINS float DEFAULT 0 NOT NULL,
	B1_PPIS float DEFAULT 0 NOT NULL,
	B1_MTBF float DEFAULT 0 NOT NULL,
	B1_MTTR float DEFAULT 0 NOT NULL,
	B1_FLAGSUG varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CLASSVE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_MIDIA varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_QTMIDIA float DEFAULT 0 NOT NULL,
	B1_QTDSER varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_VLR_IPI float DEFAULT 0 NOT NULL,
	B1_ENVOBR varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_SERIE varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_FAIXAS float DEFAULT 0 NOT NULL,
	B1_NROPAG float DEFAULT 0 NOT NULL,
	B1_ISBN varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_TITORIG varchar(50) COLLATE Latin1_General_100_BIN DEFAULT '                                                  ' NOT NULL,
	B1_LINGUA varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_EDICAO varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_OBSISBN varchar(40) COLLATE Latin1_General_100_BIN DEFAULT '                                        ' NOT NULL,
	B1_CLVL varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_ATIVO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_EMAX float DEFAULT 0 NOT NULL,
	B1_PESBRU float DEFAULT 0 NOT NULL,
	B1_TIPCAR varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_FRACPER float DEFAULT 0 NOT NULL,
	B1_VLR_ICM float DEFAULT 0 NOT NULL,
	B1_INT_ICM float DEFAULT 0 NOT NULL,
	B1_CORPRI varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_CORSEC varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_NICONE varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_ATRIB1 varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_ATRIB2 varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_ATRIB3 varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_REGSEQ varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_VLRSELO float DEFAULT 0 NOT NULL,
	B1_CODNOR varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_CPOTENC varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_POTENCI float DEFAULT 0 NOT NULL,
	B1_REQUIS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_SELO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_LOTVEN float DEFAULT 0 NOT NULL,
	B1_OK varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	B1_USAFEFO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_QTDACUM float DEFAULT 0 NOT NULL,
	B1_QTDINIC float DEFAULT 0 NOT NULL,
	B1_CNATREC varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_TNATREC varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	B1_AFASEMT float DEFAULT 0 NOT NULL,
	B1_AIMAMT float DEFAULT 0 NOT NULL,
	B1_TERUM varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_AFUNDES float DEFAULT 0 NOT NULL,
	B1_CEST varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_GRPCST varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_IAT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_IPPT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_GRPNATR varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_DTFIMNT varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_DTCORTE varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_FECP float DEFAULT 0 NOT NULL,
	B1_MARKUP float DEFAULT 0 NOT NULL,
	B1_CODPROC varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_LOTESBP float DEFAULT 0 NOT NULL,
	B1_QBP float DEFAULT 0 NOT NULL,
	B1_VALEPRE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CODQAD varchar(22) COLLATE Latin1_General_100_BIN DEFAULT '                      ' NOT NULL,
	B1_AFABOV float DEFAULT 0 NOT NULL,
	B1_VIGENC varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_VEREAN varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_DIFCNAE varchar(11) COLLATE Latin1_General_100_BIN DEFAULT '           ' NOT NULL,
	B1_ESCRIPI varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PMACNUT float DEFAULT 0 NOT NULL,
	B1_PMICNUT float DEFAULT 0 NOT NULL,
	B1_INTEG varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_HREXPO varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_CRICMS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_REFBAS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_MOPC varbinary(MAX) NULL,
	B1_USERLGI varchar(17) COLLATE Latin1_General_100_BIN DEFAULT '                 ' NOT NULL,
	B1_USERLGA varchar(17) COLLATE Latin1_General_100_BIN DEFAULT '                 ' NOT NULL,
	B1_UMOEC float DEFAULT 0 NOT NULL,
	B1_UVLRC float DEFAULT 0 NOT NULL,
	B1_PIS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_GCCUSTO varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_CCCUSTO varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_TALLA varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_PARCEI varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_GDODIF varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_VLR_PIS float DEFAULT 0 NOT NULL,
	B1_TIPOBN varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_TPREG varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_MSBLQL varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_VLCIF float DEFAULT 0 NOT NULL,
	B1_DCRE varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_DCR varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_DCRII float DEFAULT 0 NOT NULL,
	B1_TPPROD varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_DCI varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_COEFDCR float DEFAULT 0 NOT NULL,
	B1_CHASSI varchar(25) COLLATE Latin1_General_100_BIN DEFAULT '                         ' NOT NULL,
	B1_CLASSE varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_FUSTF varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_GRPTI varchar(4) COLLATE Latin1_General_100_BIN DEFAULT '    ' NOT NULL,
	B1_PRDORI varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_APOPRO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PRODREC varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ALFECOP float DEFAULT 0 NOT NULL,
	B1_ALFECST float DEFAULT 0 NOT NULL,
	B1_CFEMA float DEFAULT 0 NOT NULL,
	B1_FECPBA float DEFAULT 0 NOT NULL,
	B1_MSEXP varchar(8) COLLATE Latin1_General_100_BIN DEFAULT '        ' NOT NULL,
	B1_PAFMD5 varchar(32) COLLATE Latin1_General_100_BIN DEFAULT '                                ' NOT NULL,
	B1_PRODSBP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CODANT varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_IDHIST varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_CRDEST float DEFAULT 0 NOT NULL,
	B1_REGRISS varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_FETHAB varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ESTRORI varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_CALCFET varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PAUTFET float DEFAULT 0 NOT NULL,
	B1_CARGAE varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PRN944I varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ALFUMAC float DEFAULT 0 NOT NULL,
	B1_PRINCMG float DEFAULT 0 NOT NULL,
	B1_PR43080 float DEFAULT 0 NOT NULL,
	B1_RICM65 varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_SELOEN varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_TRIBMUN varchar(20) COLLATE Latin1_General_100_BIN DEFAULT '                    ' NOT NULL,
	B1_RPRODEP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_FRETISS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_AFETHAB float DEFAULT 0 NOT NULL,
	B1_DESBSE2 varchar(60) COLLATE Latin1_General_100_BIN DEFAULT '                                                            ' NOT NULL,
	B1_BASE2 varchar(14) COLLATE Latin1_General_100_BIN DEFAULT '              ' NOT NULL,
	B1_VLR_COF float DEFAULT 0 NOT NULL,
	B1_PRFDSUL float DEFAULT 0 NOT NULL,
	B1_TIPVEC varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_COLOR varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_RETOPER varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_COFINS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CSLL varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CNAE varchar(9) COLLATE Latin1_General_100_BIN DEFAULT '         ' NOT NULL,
	B1_ADMIN varchar(10) COLLATE Latin1_General_100_BIN DEFAULT '          ' NOT NULL,
	B1_AFACS float DEFAULT 0 NOT NULL,
	B1_AJUDIF varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ALFECRN float DEFAULT 0 NOT NULL,
	B1_CFEM varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CFEMS varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_MEPLES varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_REGESIM varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_RSATIVO varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_TFETHAB varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_TPDP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CRDPRES float DEFAULT 0 NOT NULL,
	B1_CRICMST varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_FECOP varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_CODLAN varchar(6) COLLATE Latin1_General_100_BIN DEFAULT '      ' NOT NULL,
	B1_GARANT varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PERGART float DEFAULT 0 NOT NULL,
	B1_SITTRIB varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_PORCPRL varchar(2) COLLATE Latin1_General_100_BIN DEFAULT '  ' NOT NULL,
	B1_IMPNCM float DEFAULT 0 NOT NULL,
	B1_IVAAJU varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_BASE varchar(14) COLLATE Latin1_General_100_BIN DEFAULT '              ' NOT NULL,
	B1_ZZCODAN varchar(15) COLLATE Latin1_General_100_BIN DEFAULT '               ' NOT NULL,
	B1_ZZNOGRP varchar(30) COLLATE Latin1_General_100_BIN DEFAULT '                              ' NOT NULL,
	B1_ZZOBS1 varbinary(MAX) NULL,
	B1_XFORDEN varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	B1_ZZMEN1 varchar(3) COLLATE Latin1_General_100_BIN DEFAULT '   ' NOT NULL,
	B1_ZZLEGIS varchar(250) COLLATE Latin1_General_100_BIN DEFAULT '                                                                                                                                                                                                                                                          ' NOT NULL,
	D_E_L_E_T_ varchar(1) COLLATE Latin1_General_100_BIN DEFAULT ' ' NOT NULL,
	R_E_C_N_O_ bigint DEFAULT 0 NOT NULL,
	R_E_C_D_E_L_ bigint DEFAULT 0 NOT NULL,
	CONSTRAINT SB1010_PK PRIMARY KEY (R_E_C_N_O_)
);
 CREATE NONCLUSTERED INDEX SB10101 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_COD ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10102 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_TIPO ASC  , B1_COD ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10103 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_DESC ASC  , B1_COD ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10104 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_GRUPO ASC  , B1_COD ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10105 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_CODBAR ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10106 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_PROC ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10107 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_GRUPO ASC  , B1_CODITE ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10108 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_CCCUSTO ASC  , B1_GCCUSTO ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB10109 ON dbo.SB1010 (  B1_FILIAL ASC  , B1_BASE2 ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB1010A ON dbo.SB1010 (  B1_FILIAL ASC  , B1_BASE3 ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB1010B ON dbo.SB1010 (  B1_FILIAL ASC  , B1_IDHIST ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB1010C ON dbo.SB1010 (  B1_FILIAL ASC  , B1_CONTA ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX SB1010D ON dbo.SB1010 (  B1_FILIAL ASC  , B1_CC ASC  , R_E_C_N_O_ ASC  , D_E_L_E_T_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE  UNIQUE NONCLUSTERED INDEX SB1010_UNQ ON dbo.SB1010 (  B1_FILIAL ASC  , B1_COD ASC  , R_E_C_D_E_L_ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;